<template>
  <view class="marriage-check-page"><su-navbar title="婚姻认证" statusBar />
    <view v-if="state.unauthorized" class="marriage-check-page__state"><text>登录状态已失效，请重新登录</text><button @tap="goCenter">返回认证中心</button></view><view v-else-if="state.loading" class="marriage-check-page__state">认证信息加载中…</view>
    <view v-else class="marriage-check-page__body"><view v-if="state.error" class="marriage-check-page__error"><text>{{ state.error }}</text><text @tap="load">重试</text></view><view v-else-if="!state.realVerified" class="marriage-check-page__state"><text>请先完成实名认证</text><button @tap="goRealName">去实名认证</button></view><view v-else><view class="marriage-check-page__card"><image src="/static/certification/heart.svg" /><text>已实名信息</text><text>{{ state.info.name }} {{ state.info.maskedIdCard }}</text></view><view v-if="state.status.checked" class="marriage-check-page__card"><text>{{ state.status.success ? state.status.stateLabel : '最近认证未完成' }}</text><text>{{ state.status.reason || '认证记录已更新' }}</text></view><view v-if="state.status.limitReached" class="marriage-check-page__limit">{{ state.status.limitMessage || '本月认证次数已达上限' }}</view><button :disabled="state.submitting || state.status.limitReached" @tap="submit">{{ state.submitting ? '认证中…' : '提交婚姻认证' }}</button></view></view></view>
</template>
<script setup>
import { onLoad } from '@dcloudio/uni-app'; import { reactive } from 'vue'; import sheep from '@/sheep'; import MarriageProfileApi from '@/sheep/api/marriage/profile'; import PartnerCertificationApi from '@/sheep/api/partner/certification'; import { isVerified } from '../partner-certification';
const state=reactive({ loading:true, submitting:false, unauthorized:false, error:'', realVerified:false, info:{}, status:{}, requestId:0 }); function goCenter(){ sheep.$router.go('/pages/mine-certifications/index'); } function goRealName(){ sheep.$router.go('/pages/mine-profile/nameCheck/index'); } function safeBack(){ if(sheep.$router.hasHistory()) sheep.$router.back(); else goCenter(); }
async function load(){ const requestId=++state.requestId; state.unauthorized=sheep.$store('user').isLogin!==true; state.error=''; if(state.unauthorized){state.loading=false;return;} state.loading=true; const [info,status]=await Promise.all([MarriageProfileApi.getRealNameInfo(),PartnerCertificationApi.getMarriageStatus()]); if(requestId!==state.requestId||!sheep.$store('user').isLogin)return; state.loading=false; if(info?.code===0&&status?.code===0){state.info=info.data||{};state.status=status.data||{};state.realVerified=isVerified(state.info.realVerified);}else state.error=info?.msg||status?.msg||'认证信息加载失败，请重试'; }
async function submit(){if(state.submitting||state.status.limitReached||!state.realVerified)return;if(!sheep.$store('user').isLogin){state.unauthorized=true;return;}state.submitting=true;const result=await PartnerCertificationApi.verifyMarriage();state.submitting=false;if(!sheep.$store('user').isLogin){state.unauthorized=true;return;}if(result?.code===0){uni.showToast({title:result.data?.success?(result.data?.reused?'已复用历史认证结果':result.data?.stateLabel||'认证完成'):(result.data?.reason||'认证未完成'),icon:'none'});load();}else uni.showToast({title:result?.msg||'认证失败，请重试',icon:'none'});}
onLoad(load);
</script>
<style scoped lang="scss">.marriage-check-page { min-height:100vh; padding:0 28rpx; background:var(--marriage-soft); color:var(--marriage-text); &__header { height:104rpx; display:flex; align-items:center; justify-content:center; position:relative; font-size:34rpx; font-weight:600; > text:first-child { position:absolute; left:0; font-size:58rpx; } } &__body { padding-top:35rpx; } &__card, &__limit, &__error { display:flex; flex-direction:column; gap:14rpx; padding:28rpx; margin-bottom:22rpx; border-radius:16rpx; background:var(--marriage-surface); font-size:28rpx; box-shadow:var(--marriage-shadow); image { width:100rpx; height:100rpx; } text:last-child { color:var(--marriage-muted); font-size:25rpx; } } &__limit, &__error { color:var(--marriage-primary-pressed); } &__limit { background:var(--marriage-orange); } &__error { flex-direction:row; } button { width:100%; background:var(--marriage-primary); color:#fff; border-radius:999rpx; } button[disabled] { opacity:.45; } &__state { min-height:55vh; display:flex; flex-direction:column; align-items:center; justify-content:center; gap:28rpx; button { width:auto; } } }</style>
